#!/data/data/com.termux/files/usr/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BIN="$PREFIX/bin/claude-t"
printf '#!/data/data/com.termux/files/usr/bin/bash\nexec python "%s/claude-termux.py" "$@"\n' "$SCRIPT_DIR" > "$BIN"
chmod +x "$BIN"
echo "[+] Installed. Run: claude-t"
echo ""
echo "If you don't have a local model yet:"
echo "  pkg install ollama"
echo "  ollama serve &"
echo "  ollama pull qwen3:1.7b"
echo "  claude-t"
